### PR TITLE
Fix Bug#185

### LINKED ISSUE #185: remarkProperty doesn't guard against unique prefixes
ie remarkProperty 1 r/hello r/ hehe the remark is only hehe

### PR DESCRIPTION
**Pull request by ongyongyue**
Close #185

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/RemarkPropertyCommandParser.java [hunk 1]
```diff
@@ -25,6 +25,10 @@ public RemarkPropertyCommand parse(String args) throws ParseException {
                     String.format(MESSAGE_INVALID_COMMAND_FORMAT, RemarkPropertyCommand.MESSAGE_USAGE), pe);
         }
 
+        if (argMultimap.getAllValues(PREFIX_REMARK).size() > 1) {
+            throw new ParseException("Only one remark is allowed. Please provide a single r/ prefix.");
+        }
```
Comment (wuikong) [inline src/main/java/seedu/address/logic/parser/RemarkPropertyCommandParser.java]: Instead of making a custom error message, perhaps use `argMultimap.verifyNoDuplicatePrefixesFor()`?
