### PR TITLE
Fix alpha bug

### LINKED ISSUE #172: addProperty allows duplicates if filterClient is used
Only 1 property should linked to 1 person. However, if we filterCLient, then add a property that its already owned by someone else, it works when it actually shouldnt. Below is a sequence of events

addClient n/Alice c/91111111 e/alice@test.com
addClient n/Bob c/92222222 e/bob@test.com
addProperty i/1 a/123 Street pr/500000 s/1000 type/Condo
filterClient n/Bob
addProperty i/1 a/123 Street pr/500000 s/1000 type/Condo

### PR DESCRIPTION
**Pull request by LIU-ZHIYUAN-source**
Fixes #172 #174 #177 #187 #191

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditPropertyCommand.java [hunk 1]
```diff
@@ -71,6 +73,14 @@ public CommandResult execute(Model model) throws CommandException {
         Property propertyToEdit = lastShownPropertyList.get(index.getZeroBased());
         Property editedProperty = createEditedProperty(propertyToEdit, editPropertyDescriptor);
 
+        for (Person person : model.getAddressBook().getPersonList()) {
+            for (Property p : person.getProperties()) {
+                if (!p.equals(propertyToEdit) && p.isSameProperty(editedProperty)) {
+                    throw new CommandException(MESSAGE_DUPLICATE_PROPERTY);
```
Comment (wuikong) [inline src/main/java/seedu/address/logic/commands/EditPropertyCommand.java]: This checks if *anyone* already owns the target edited property, not just the client that owns the propertyToEdit. Maybe we can edit MESSAGE_DUPLICATE_PROPERTY?

Looks like stream can be used here, it could improve runtime, up to you
