### PR TITLE
Fix code alpha bugs

### LINKED ISSUE #226: [PE-D][Tester A] Bug: Duplicate properties with same address can be added despite address being defined as unique identifier
Description:
The application allows multiple properties with the same address to be added to two different clients just by changing one of the other parameters excluding the address, even though the address is defined as the unique identifier of a property. This may lead to duplicate address entries and creates ambiguity when identifying or managing properties.

Steps to reproduce:

Prerequisite:
Have two clients in the client list

Steps:
`addProperty i/1 a/test pr/1000000 s/1000 type/HDB`
`addProperty i/2 a/test pr/1000000 s/1000 type/Condo`

Expected:
Error message saying it is a property that is owned by someone else
Actual:
Adds the property anyway

Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #229: [PE-D][Tester E] addProperty allows same address to be added to different clients unless all fields match
### Summary
addProperty only detects duplicates across clients when property address, price, size, and type all match exactly.
<br>
This allows multiple clients to “own” the same address as long as any field differs, which contradicts the User Guide specification that “A property cannot be assigned to multiple clients. Attempting to add a property that is already owned by another client will result in an error.”

### Steps to Reproduce
Using the sample data provided,

1. Add a property to Client 1:
`addProperty i/1 a/311 Clementi Ave 2, #02-25 pr/1200000 s/1200 type/HDB`

2. Add the same address to Client 2, but change one field (e.g. size):
`addProperty i/2 a/311 Clementi Ave 2, #02-25 pr/1200000 s/1300 type/HDB`

3. Add the same address to Client 3, but change type:
`addProperty i/3 a/311 Clementi Ave 2, #02-25 pr/1200000 s/1200 type/Condo`

### Expected Behavior
- The system should block adding a property with an address that already exists under any client.
- Error message should appear: "This property is already owned by another client."

### Actual Behavior
- The system only blocks duplicates (same address, case-sensitive) **within** the same client.
- Different clients can own the same address as long as **any other field differs** (price/size/type).
- This results in multiple clients owning the same physical property.

### Screenshots

Image

### Why this is a problem

- Violates documented behaviour in the User Guide.
- Breaks real‑world semantics (a property address is unique; the same unit cannot be both a 'HDB' and 'Condo' type, and cannot be of different sizes at the same time))
- Leads to inconsistent and misleading data (same address appears multiple times with different attributes).
- Affects downstream features such as filtering, matching, and viewing property details.

### Severity / Type
- Severity: Medium
   - Data inconsistency that affects core functionality but does not crash the app.

- Type: FunctionalityBug
   - Behaviour contradicts the User Guide and expected domain logic.

### Additional Notes
If the intention was to allow the same physical property to appear under different clients because they owned it at different times, the current data model does not support this interpretation. Historical ownership would require additional distinguishing fields (e.g. ownership period, transaction status, sale date). Since no such fields exist and the User Guide does not mention historical or temporal ownership, the current behaviour appears unintended.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #230: [PE-D][Tester B] addClient rejects legitimate client names containing common punctuation
Description:
The app rejects legitimate client names containing common punctuation such as hyphens and slashes. This prevents users from adding realistic names such as "Aaron-Pierce" and "Ramadan S/G".

Steps to reproduce:
1. Launch the app.
2. Run:
   addClient n/Aaron-Pierce c/91234567 e/aaronpierce@example.com
3. Run:
   addClient n/Ramadan S/G c/92345678 e/ramadansg@example.com

Expected:
The client should be added successfully.

Actual:
Both inputs are rejected with the error message:
"Names should only contain alphanumeric characters and spaces, and it should not be blank"

Why this is problematic:
Legitimate real-world names can contain punctuation such as hyphens and slashes. The User Guide documents the addClient format as
addClient n/NAME c/CONTACT e/EMAIL [t/TAG]...
but does not state that such characters are disallowed.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #241: [PE-D][Tester C] Client name is too restrictive to allow for use of some legal names
Image

Image

Intended use of client management would be to use client's legal name, but this creates problems due to restrictions. Common names in Singapore in the form of "Chinese name, english name" (commas) and "First name S/O parent name" (slash) or hyphens (-) would require work arounds. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #251: [PE-D][Tester C] The same property can be duplicated if assigned to different clients with size or price changed
Image

When adding property to the same client, the name being the same is the equality condition. This implies that "same property" means the name being the same. With the same name and different price, size or type, different people can own the property with the same name. This can happen easily if the user mistypes the price or size by adding or removing a 0.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #272: [PE-D][Tester B] App blocks adding two distinct clients who share the same name
Description:
The app rejects a second client entry when the new client has the same full name as an existing one, even if the phone number and email are different.

Steps to reproduce:
1. Run:
   addClient n/Alex Tan c/111 e/a@example.com
2. Run:
   addClient n/Alex Tan c/222 e/b@example.com

Expected:
The app should allow both clients to be stored, or at least warn the user and allow disambiguation.

Actual:
The second client is rejected as a duplicate.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #274: [PE-D][Tester B] Duplicate detection misses case-only name variations such as Alex Tan and alex tan
Description:
The app allows case-only variants of the same client name to be stored as separate clients. For example, `Alex Tan` and `alex tan` are accepted as two different entries even though names are not case-sensitive in normal usage.

Steps to reproduce:
1. Run:
   addClient n/Alex Tan c/111 e/a@example.com
2. Run:
   addClient n/alex tan c/222 e/b@example.com
3. Run:
   list

Expected:
The app should at least flag this as a likely duplicate or warn the user before allowing both entries.

Actual:
Both entries are accepted and shown as separate clients.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #287: [PE-D][Tester B] DG logic section still documents delete 1 and DeleteCommandParser, which do not exist in ClientVault
Description:
The Developer Guide logic walkthrough still explains command execution using the old AB3-style `delete 1` command and `DeleteCommandParser`, even though ClientVault uses `deleteClient` and `deleteProperty`.

Steps to reproduce:
1. Open the Developer Guide.
2. Go to the Logic component / command execution walkthrough.
3. Read the example sequence and parser references in that section.

Expected:
The Developer Guide should document the actual commands and parsers used by ClientVault.

Actual:
It still refers to AB3 concepts such as `delete 1` and `DeleteCommandParser`.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #299: [PE-D][Tester D] Outdated Commands in Developer Guide
The Developer Guide PDF file contains instructions or examples using the `delete 1` command. However, this command is not implemented in the current product. Maybe should try to use `deleteClient 1` instead? 

- Screenshot 
Image

Image

-------------
Labels: `severity.Medium` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by ongyongyue**
Close #274 , Close #272 , Close #230, Close #229, Close #251, Close #241, Close #226
Fix #287, Fix #299

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -137,7 +137,8 @@ public boolean isSamePerson(Person otherPerson) {
         }
 
         return otherPerson != null
-                && otherPerson.getName().equals(getName());
```
Comment (LIU-ZHIYUAN-source) [inline src/main/java/seedu/address/model/person/Person.java:140]: Not sure if this need to be removed or not.
